version: '3'

services:
  traefik:
    image: traefik:1.7.4
    restart: always
    ports:
      - 80:80
      - 8082:8082
      - 8083:8083
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/anjmao/traefik/traefik.toml:/traefik.toml
    container_name: traefik

networks:
  web:
    external: true