version: '3.3'

services:
  traefik:
    image: traefik:1.7.4
    deploy:
      placement:
        constraints: [node.role==manager]
    ports:
      - 80:80
      - 8082:8082
      - 8083:8083
    networks:
      - default
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/anjmao/traefik.toml:/traefik.toml

networks:
  traefik:
    external: true